(defun petscii-font-preview ()
  "Create a buffer showing all PETSCII characters using C64 Pro Mono font."
  (interactive)
  (let ((buf (get-buffer-create "*PETSCII Font Preview*")))
    (with-current-buffer buf
      (erase-buffer)
      (dotimes (row 16)
        (dotimes (col 16)
          (insert (format "%c " (+ (* row 16) col))))
        (insert "\n"))
      (setq buffer-read-only t)
      (face-remap-add-relative 'default :family "C64 Pro Mono" :height 120)
      (goto-char (point-min)))
    (switch-to-buffer buf)))


(defvar petscii-control-code-table
  '(("{clr}"     . 147)
    ("{home}"    . 19)
    ("{inst-del}". 20)
    ("{return}"  . 13)
    ("{rvs-on}"  . 18)
    ("{rvs-off}" . 146)
    ("{pi}"      . 255)
    ("{up}"      . 145)
    ("{down}"    . 17)
    ("{left}"    . 157)
    ("{right}"   . 29)
    ("{stop}"    . 3)
    ("{runstop}" . 5)
    ("{quote}"   . 34)
    ("{pound}"   . 156)
    ("{asterisk}". 42)
    ("{arrow}"   . 30)
    ("{bell}"    . 7)
    ("{esc}"     . 27)
    ("{tab}"     . 9)
    ("{black}"   . 144)
    ("{white}"   . 5)
    ("{red}"     . 28)
    ("{cyan}"    . 159)
    ("{purple}"  . 156)
    ("{green}"   . 30)
    ("{blue}"    . 31)
    ("{yellow}"  . 158))
  "Mapping of petcat control codes to PETSCII character codes.")

(defun petscii-show-char (code)
  "Show the PETSCII character for a given petcat control CODE."
  (interactive
   (list (completing-read "Enter petcat control code: " (mapcar #'car petscii-control-code-table))))
  (let ((char-code (cdr (assoc code petscii-control-code-table))))
    (if char-code
        (message "PETSCII character for %s: %c (code %d)" code char-code char-code))))


(defvar petscii-petcat-table
  '(("{clr}"     . 147)
    ("{home}"    . 19)
    ("{inst-del}". 20)
    ("{return}"  . 13)
    ("{rvs-on}"  . 18)
    ("{rvs-off}" . 146)
    ("{pi}"      . 255)
    ("{up}"      . 145)
    ("{down}"    . 17)
    ("{left}"    . 157)
    ("{right}"   . 29)
    ("{stop}"    . 3)
    ("{runstop}" . 5)
    ("{quote}"   . 34)
    ("{pound}"   . 156)
    ("{asterisk}". 42)
    ("{arrow}"   . 30)
    ("{bell}"    . 7)
    ("{esc}"     . 27)
    ("{tab}"     . 9)
    ("{black}"   . 144)
    ("{white}"   . 5)
    ("{red}"     . 28)
    ("{cyan}"    . 159)
    ("{purple}"  . 156)
    ("{green}"   . 30)
    ("{blue}"    . 31)
    ("{yellow}"  . 158))
  "Mapping of petcat control codes to PETSCII codes.")

(defun petscii-insert-unicode-char (code)
  "Insert the Unicode character for a given petcat control CODE using C64 Pro Mono font."
  (interactive
   (list (completing-read "Enter petcat control code: " (mapcar #'car petscii-petcat-table))))
  (let* ((petscii (cdr (assoc code petscii-petcat-table)))
         (unicode (+ #xEF40 petscii)))
    (if petscii
        (insert (char-to-string unicode))
      (message "Unknown control code: %s" code))))
