* TrueType Font im Emacs benutzen

Um einen **TTF-Font** (TrueType Font) wie z.B. einen Retro-Font für
deinen `basic65-mode` in Emacs zu verwenden, gibt es zwei Ansätze – je
nachdem, ob du ihn **global** oder **nur für einen bestimmten Mode**
nutzen möchtest.

Vorbedingung ist allerdings, dass der Fonts betriebssystemseitig
installiert ist. Für Windows kann man das hier nachlesen:
https://www.heise.de/tipps-tricks/Windows-10-Schriftarten-installieren-4178982.html

Für Linux kann man hier nachschlagen:
https://linux-bibel.at/index.php/2023/09/03/schriften-fonts-unter-linux-installieren/


---

** Schritt-für-Schritt: TTF-Font in Emacs nutzen

***  1. Font installieren (Systemweit)

Stelle sicher, dass der Font auf deinem System installiert ist:

- Unter **Windows**: Rechtsklick auf die `.ttf`-Datei → „Installieren“
- Unter **Linux**: Kopiere die Datei nach `~/.fonts/` oder
  `~/.local/share/fonts/` und führe `fc-cache -fv` aus

---

***  2. Font in Emacs verfügbar machen

Du kannst prüfen, ob Emacs den Font erkennt:

#+begin_src lisp
(insert (prin1-to-string (font-family-list)))
#+end_src

Das zeigt dir alle verfügbaren Font-Namen. Suche nach deinem Font,
z.B. `"C64 Pro Mono"` oder `"Pixel Emulator"`.

---

***  3. Font global setzen (optional)
#+begin_src lisp
(set-frame-font "C64 Pro Mono-12" t t)
#+end_src
---

***  4. Font **nur für `basic65-mode`** setzen

Hier ein Beispiel, wie du den Font nur für deinen eigenen Mode
aktivierst:

#+begin_src lisp
  (defun basic65-set-font ()
    "Setzt Retro-Font fuer BASIC65-Mode."
    (face-remap-add-relative 'default :family "C64 Pro Mono" :height 120))

  (add-hook 'basic65-mode-hook *'basic65-set-font)
#+end_src

Das funktioniert, wenn du `basic65-mode` als eigenen Major Mode
definiert hast. 


face-remap-add-relative: Diese Funktion verändert das Aussehen (Face)
nur im aktuellen Buffer, und zwar relativ zur bestehenden Darstellung.

'default: Das ist die Standard-Schriftart für normalen Text in
Emacs. Du veränderst also die Hauptschriftart im Buffer.

:family "Courier New": Du setzt die Schriftfamilie auf "Courier New" –
eine klassische Monospace-Schrift.

:height 200: Die Schriftgröße wird auf 200/10 = 20 pt gesetzt. Emacs
verwendet hier eine Skalierung in 1/10 pt.

---

***  5. Optional: Font für bestimmte Fenster oder Buffers

Du kannst auch gezielt in bestimmten Buffern den Font setzen,
z.B. für ein REPL-Fenster oder ein Emulator-Log.

---

**  Bonus: Font-Vorschau

Wenn du magst, kannst du auch ein kleines Snippet schreiben, das dir
den Font in einem Test-Buffer zeigt:

#+begin_src lisp
  (defun font-preview (font-name)
    "Zeigt eine Vorschau des Fonts FONT-NAME."
    (interactive "sFont name: ")
    (let ((buf
  	 (get-buffer-create "*Font Preview*")))
      (with-current-buffer buf
        (erase-buffer) (insert "10 PRINT \"HELLO MEGA65\"\n20 GOTO 10")
        (face-remap-add-relative 'default :family font-name :height 120))
      (display-buffer buf)))
#+end_src
---


* Control Codes
A control code within the PETSCII character set is a special
non-printable character used on Commodore computers to control the
behavior of the screen or printer, rather than display a visible
glyph. These codes, found in specific byte ranges such as $00-$1F and
$80-$9F, manipulate screen layout and features like text color, cursor
movement, and clearing the screen, influencing how subsequent
characters are displayed.

What PETSCII Control Codes Do: Screen Control: They can change aspects
of the display, such as setting the text color or controlling the
cursor.  Printing Control: Control codes can also affect how
information is sent to a printer or saved to a disk or tape file.
Functionality, Not Visibility: Unlike printable characters (letters,
numbers, symbols), control codes perform an action without showing any
character on the screen themselves.

Examples of Use: In Commodore BASIC, a program might use PRINT
CHR$(65) to display the letter 'A', but a control code like CHR$(147)
would clear the screen.  Specific control characters can include
commands like "RVS ON" (reverse text) or "CLR" (clear screen).

Where They Are Used: Commodore Computers: PETSCII was the standard
character encoding for Commodore computers like the VIC-20 and C64,
and control codes are embedded in BASIC programs and text files.
Character Set Composition: The 256-byte PETSCII set is a mix of
printable characters, including unique graphics glyphs, and these
non-printable control codes.

https://www.c64-wiki.de/wiki/Petcat



Unter Unix ist es ebenso möglich, mit Petcat BASIC-Programme umzuwandeln:

Zuerst ein Terminal-Fenster öffnen und wie bei Windows empfohlen, ein
eigenes Verzeichnis erstellen.  Auch hier gilt, dass der BASIC-Text in
Kleinbuchstaben vorliegen muss, was mit "tr '[:upper:]' '[:lower:]'<
IN.BAS > OUT.BAS" einfach zu machen ist.  Umwandeln geht dann mit den
gleichen Befehlen wie unter Windows im Kommandozeilenfenster.


Konvertieren eines zuvor erzeugten PRG Files zurück nach BASIC 65:

PS E:> E:\projects\MEGA65\petcat.exe -v -65 -o convert.bas -- .\convert.prg


* PETSCII
https://style64.org/petscii/

https://www.c64-wiki.com/wiki/PETSCII_Codes_in_Listings




* petcat control codes:
'(
("\f" . "{\f}")
("$0a" . "{$0a}")
("$6a" . "{$6a}")
("$6b" . "{$6b}")
("$6c" . "{$6c}")
("$6d" . "{$6d}")
("$6e" . "{$6e}")
("$6f" . "{$6f}")
("$7a" . "{$7a}")
("$7b" . "{$7b}")
("$7c" . "{$7c}")
("$7d" . "{$7d}")
("$7e" . "{$7e}")
("$7f" . "{$7f}")
("$8f" . "{$8f}")
("$60" . "{$60}")
("$61" . "{$61}")
("$62" . "{$62}")
("$63" . "{$63}")
("$64" . "{$64}")
("$65" . "{$65}")
("$66" . "{$66}")
("$67" . "{$67}")
("$68" . "{$68}")
("$69" . "{$69}")
("$70" . "{$70}")
("$71" . "{$71}")
("$72" . "{$72}")
("$73" . "{$73}")
("$74" . "{$74}")
("$75" . "{$75}")
("$76" . "{$76}")
("$77" . "{$77}")
("$78" . "{$78}")
("$79" . "{$79}")
("$80" . "{$80}")
("$82" . "{$82}")
("$83" . "{$83}")
("$84" . "{$84}")
("$a0" . "{$a0}")
("$de" . "{$de}")
("$e0" . "{$e0}")
("$e1" . "{$e1}")
("$e2" . "{$e2}")
("$e3" . "{$e3}")
("$e4" . "{$e4}")
("$e5" . "{$e5}")
("$e6" . "{$e6}")
("$e7" . ""{$e7})
("$e8" . ""{$e8})
("$e9" . "{$e9}")
("$ea" . "{$ea}")
("$eb" . "{$eb}")
("$ec" . "{$ec}")
("$ed" . "{$ed}")
("$ee" . "{$ee}")
("$ef" . "{$ef}")
("$f0" . "{$f0}")
("$f1" . "{$f1}")
("$f2" . "{$f2}")
("$f3" . "{$f3}")
("$f4" . "{$f4}")
("$f5" . "{$f5}")
("$f6" . "{$f6}")
("$f7" . "{$f7}")
("$f8" . "{$f8}")
("$f9" . "{$f9}")
("$fa" . "{$fa}")
("$fb" . "{$fb}")
("$fc" . "{$fc}")
("$fd" . "{$fd}")
("$fe" . "{$fe}")
("blk" . "{blk}")
("blu" . "{blu}")
("brn" . "{brn}")
("CBM--" ." "{CBM--}")
("CBM-@" ." "{CBM-@}")
("CBM-*" ." "{CBM-*}")
("CBM-+" ." "{CBM-+}")
("CBM-A" ." "{CBM-A}")
("CBM-B" ." "{CBM-B}")
("CBM-C" ." "{CBM-C}")
("CBM-D" ." "{CBM-D}")
("CBM-E" ." "{CBM-E}")
("CBM-F" ." "{CBM-F}")
("CBM-G" ." "{CBM-G}")
("CBM-H" ." "{CBM-H}")
("CBM-I" ." "{CBM-I}")
("CBM-J" . "{CBM-J}")
("CBM-K" . "{CBM-K}")
("CBM-L" . "{CBM-L}")
("CBM-M" . "{CBM-M}")
("CBM-N" . "{CBM-N}")
("CBM-O" . "{CBM-O}")
("CBM-P" . "{CBM-P}")
("CBM-POUND" . "{CBM-POUND}")
("CBM-Q" . "{CBM-Q}")
("CBM-R" . "{CBM-R}")
("CBM-S" . "{CBM-S}")
("CBM-T" . "{CBM-T}")
("CBM-U" . "{CBM-U}")
("CBM-V" . "{CBM-V}")
("CBM-W" . "{CBM-W}")
("CBM-X" . "{CBM-X}")
("CBM-Y" . "{CBM-Y}")
("CBM-Z" . "{CBM-Z}")
("clr" . "{clr}")
("CTRL-A" ". "{CTRL-A}")
("CTRL-B" ". "{CTRL-B}")
("CTRL-D" ". "{CTRL-D}")
("CTRL-F" ". "{CTRL-F}")
("CTRL-G" ". "{CTRL-G}")
("CTRL-K" ". "{CTRL-K}")
("CTRL-O" ". "{CTRL-O}")
("CTRL-P" ". "{CTRL-P}")
("CTRL-U" ". "{CTRL-U}")
("CTRL-V" ". "{CTRL-V}")
("CTRL-W" ". "{CTRL-W}")
("CTRL-X" ". "{CTRL-X}")
("CTRL-Y" ". "{CTRL-Y}")
("CTRL-Z" ". "{CTRL-Z}")
("cyn" . "{cyn}")
("del" . "{del}")
("dish" . "{dish}")
("down" . "{down}")
("ensh" . "{ensh}")
("esc" . "{esc}")
("f1" . "{f1}")
("f2" . "{f2}")
("f3" . "{f3}")
("f4" . "{f4}")
("f5" . "{f5}")
("f6" . "{f6}")
("f7" . "{f7}")
("f8" . "{f8}")
("grn" . "{grn}")
("gry1" . "{gry1}")
("gry2" . "{gry2}")
("gry3" . "{gry3}")
("home" . "{home}")
("inst" . "{inst}")
("lblue" . "{lblue}")
("left" . "{left}")
("een" . "reen}")
("lred" . "{lred}")
("null" . "{null}")
("orng" . "{orng}")
("pur" . "{pur}")
("red" . "{red}")
("rght" . "{rght}")
("rvof" . "{rvof}")
("rvon" . "{rvon}")
("SHIFT--" . "{SHIFT--}")
("SHIFT-@" . "{SHIFT-@}")
("SHIFT-*" . "{SHIFT-*}")
("SHIFT-+" . "{SHIFT-+}")
("SHIFT-POUND" . "{SHIFT-POUND}")
("space" . "{space}")
("stop" . "{stop}")
("stret" . "{stret}")
("swlc" . "{swlc}")
("swuc" . "{swuc}")
("up" . "{up}")
("wht" . "{wht}))


* petscii nach unicode


efa0 - efde


** Mapping C64 Pro Mono Font to Unicode

For further reference see: https://style64.org/petscii/

Tabelle für Kleinbuchstaben Modus: cbm + shift gleichzeitig

| Glyph | RVS On Lower Upper | comment |
|-------+--------------------+---------|
|       | efa0               | ' space |
| !     | efa1               |         |
| "     | efa2               |         |
| #     | efa3               |         |
| $     | efa4               |         |
| %     | efa5               |         |
| &     | efa6               |         |
| '     | efa7               |         |
| (     | efa8               |         |
| )     | efa9               |         |
| *     | efaa               |         |
| +     | efab               |         |
| ,     | efac               |         |
|-------+--------------------+---------|
| .     | efae               |         |
| /     | efaf               |         |
| 0     | efb0               |         |
| 1     | efb1               |         |
| 2     | efb2               |         |
| 3     | efb3               |         |
| 4     | efb4               |         |
| 5     | efb5               |         |
| 6     | efb6               |         |
| 7     | efb7               |         |
| 8     | efb8               |         |
| 9     | efb9               |         |
| :     | efba               |         |
| ;     | efbb               |         |
| <     | efbc               |         |
| =     | efbd               |         |
| >     | efbe               |         |
| ?     | efbf               |         |
|-------+--------------------+---------|
| @     | ef80               |         |
| A     | ef81               |         |
| B     | ef82               |         |
| C     | ef83               |         |
| D     | ef84               |         |
| E     | ef85               |         |
| F     | ef86               |         |
| G     | ef87               |         |
| H     | ef88               |         |
| I     | ef89               |         |
| J     | ef8a               |         |
| K     | ef8b               |         |
| L     | ef8c               |         |
| M     | ef8d               |         |
| N     | ef8e               |         |
| O     | ef9f               |         |
| P     | ef90               |         |
| Q     | ef91               |         |
| R     | ef92               |         |
| S     | ef93               |         |
| T     | ef94               |         |
| U     | ef95               |         |
| V     | ef96               |         |
| W     | ef97               |         |
| X     | ef98               |         |
| Y     | ef99               |         |
| Z     | ef9a               |         |
| [     | ef9b               |         |
|     | ef9c               |         |
| ]     | ef9d               |         |
|     | ef9e               |         |
|     | ef9f               |         |
|-------+--------------------+---------|
|     | efc0               |         |
|     | efc1               |         |
|     | efc2               |         |
|     | efc3               |         |
|     | efc4               |         |
|     | efc5               |         |
|     | efc6               |         |
|     | efc7               |         |
|     | efc8               |         |
|     | efc9               |         |
|     | efca               |         |
|     | efcb               |         |
|     | efcc               |         |
|     | efcd               |         |
|     | efce               |         |
|     | efcf               |         |
|     | efd0               |         |
|     | efd1               |         |
|     | efd2               |         |
|     | efd3               |         |
|     | efd4               |         |
|     | efd5               |         |
|     | efd6               |         |
|     | efd7               |         |
|     | efd8               |         |
|     | efd9               |         |
|     | efda               |         |
|     | efdb               |         |
|     | efdc               |         |
|     | efdd               |         |
|     | efde               |         |
|     | efdf               |         |
|-------+--------------------+---------|

(insert (

  [U+E0A0]
  [U+E0A1]
  [U+E0A2]
  [U+E0A3]
_
  [U+E0A5]
  [U+E0A6]
  [U+E0A7]
  [U+E0A8]
  [U+E0A9]
  [U+E0AA]
  
  [U+E0AC]
  [U+E0AD]
  [U+E0AE]
  [U+E0AF]
  [U+E0B0]
  [U+E0B1]
  [U+E0B2]
  [U+E0B3]
  [U+E0B4]
  [U+E0B5]
  [U+E0B6]
  [U+E0B7]
  [U+E0B8]
  [U+E0B9]
  [U+E0BA]
  [U+E0BB]
  [U+E0BC]
  [U+E0BD]
  [U+E0BE]
  [U+E0BF]
  [U+E0C0]
  [U+E0C1]
  [U+E0C2]
  [U+E0C3]
  [U+E0C4]
  [U+E0C5]
  [U+E0C6]
  [U+E0C7]
  [U+E0C8]
  [U+E0C9]
  [U+E0CA]
  [U+E0CB]
  [U+E0CC]
  [U+E0CD]
  [U+E0CE]
  [U+E0CF]
  [U+E0D0]
  [U+E0D1]
  [U+E0D2]
  [U+E0D3]
  [U+E0D4]
  [U+E0D5]
  [U+E0D6]
  [U+E0D7]
  [U+E0D8]
  [U+E0D9]
  [U+E0DA]
  [U+E0DB]
  [U+E0DC]
  [U+E0DD]
  [U+E0DE]
  [U+E0DF]
  [U+E0E0]
  [U+E0E1]
  [U+E0E2]
  [U+E0E3]
  [U+E0E4]
  [U+E0E5]
  [U+E0E6]
  [U+E0E7]
  [U+E0E8]
  [U+E0E9]
  [U+E0EA]
  [U+E0EB]
  [U+E0EC]
  [U+E0ED]
  [U+E0EE]
  [U+E0EF]
  [U+E0F0]
  [U+E0F1]
  [U+E0F2]
  [U+E0F3]
  [U+E0F4]
  [U+E0F5]
  [U+E0F6]
  [U+E0F7]
  [U+E0F8]
  [U+E0F9]
  [U+E0FA]
  [U+E0FB]
  [U+E0FC]
  [U+E0FD]
  [U+E0FE]
  [U+EFDE]



* Other useful source
https://m65digest.substack.com/p/fun-with-petscii
https://mega65.atlassian.net/wiki/spaces/MEGA65/pages/27492353/Using+petcat+for+cross-developing+BASIC+programs

https://mega65.atlassian.net/wiki/spaces/MEGA65/overview?mode=global


rem Unicode -> petscii control code


efd3 -> $d3 -> {clr} (petcat vice 3.3)

ef85 -> $85 -> {wht}
ef92 -> $92 -> {rvon} 
efd2 -> $d2 -> {rvof}

